import { downloadBlob, sanitizeFilename } from '../../figureExport';

// Markdown report assembly. The deterministic sections (model summary, fit
// metrics, convergence) are built from the same run context the model sees, so
// the tables never depend on the LLM; the narrative is grafted in clearly
// labeled as generated text.

const formatCell = (value) => (value == null ? '—' : String(value));

const table = (headers, rows) => [
    `| ${headers.join(' | ')} |`,
    `| ${headers.map(() => '---').join(' | ')} |`,
    ...rows.map((row) => `| ${row.map(formatCell).join(' | ')} |`)
].join('\n');

const structureSection = (structure) => {
    if (!structure) return '_No model structure detected._';
    const rows = [
        ['Cell (Å)', structure.cell_A?.join(' × ')],
        ['Angles (°)', structure.angles_deg?.join(' · ')],
        ['Supercell', structure.supercell?.join(' × ')],
        ['Total atoms', structure.total_atoms],
        ['Elements', structure.elements
            ? Object.entries(structure.elements).map(([element, count]) => `${element}: ${count}`).join(', ')
            : null],
        ['Detected space group', structure.space_group]
    ].filter(([, value]) => value != null);
    return table(['Property', 'Value'], rows);
};

const datasetsSection = (datasets) => {
    if (!datasets?.length) return '_No fitted datasets detected._';
    return table(
        ['Dataset', 'Kind', 'Rwp'],
        datasets.map((entry) => [entry.title || entry.kind, entry.kind, entry.rwp])
    );
};

const convergenceSection = (convergence) => {
    if (!convergence) return '_No R-value / chi-squared history detected._';
    const rows = [
        ['Steps recorded', convergence.n_steps],
        ['ln(χ²) first → last', `${convergence.first} → ${convergence.last}`],
        ['ln(χ²) min / max', `${convergence.min} / ${convergence.max}`],
        ['Recent slope (per step)', convergence.recent_slope_per_step],
        ['Final χ²', convergence.final_chi_squared]
    ].filter(([, value]) => value != null);
    return table(['Quantity', 'Value'], rows);
};

export const buildReportMarkdown = (context, narrative, { model, temperature, generatedAt = new Date() } = {}) => {
    const lines = [
        `# RMCProfile run report — ${context.run}`,
        '',
        `Generated ${generatedAt.toISOString()} by the rmc-toolkits AI Assistant (experimental).`,
        '',
        '## Model summary',
        '',
        structureSection(context.structure),
        '',
        '## Fit metrics',
        '',
        datasetsSection(context.datasets),
        '',
        '## Convergence',
        '',
        convergenceSection(context.convergence),
        ''
    ];
    if (narrative) {
        lines.push(
            '## AI assessment',
            '',
            `> Generated by \`${model || 'unknown model'}\` — verify every statement against the data before relying on it.`,
            '',
            narrative.trim(),
            ''
        );
    }
    lines.push(
        '---',
        '',
        `_Provenance: rmc-toolkits AI Assistant · provider model \`${model || 'n/a'}\``
            + `${temperature != null ? ` · temperature ${temperature}` : ''} · run \`${context.run}\`._`,
        ''
    );
    return lines.join('\n');
};

export const downloadReport = (markdown, runName) => {
    const blob = new Blob([markdown], { type: 'text/markdown;charset=utf-8' });
    downloadBlob(blob, `${sanitizeFilename(runName || 'run')}-report.md`);
};
