# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2026 Tsung-Han Yang

"""Golden fixture for the static-mode JS engine parity tests.

Runs the Python Auto StoG engine on the shared synthetic model and writes
web_app/frontend/src/__tests__/fixtures/autoscale_fixture.json. Regenerate
whenever the engine's math changes:

    .venv/bin/python tests/generate_autoscale_fixture.py
"""

import json
from pathlib import Path

import numpy as np

from rmc_toolkits.scaling import ScalingConfig, autoscale, level_sweep, scale_pipeline
from rmc_toolkits.transforms import fq_to_sq, g_to_gpdf, gpdf_to_fq

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "web_app" / "frontend" / "src" / "__tests__" / "fixtures" / "autoscale_fixture.json"

RHO0, B2 = 0.05, 0.02
A_TRUE, B_TRUE = 10.0, -9.0


def synthetic_g(r):
    """Same synthetic model as tests/test_scaling.py (kept in sync)."""
    onset = 0.5 * (1.0 + np.tanh((r - 2.65) / 0.07))
    peak = 1.6 * np.exp(-0.5 * ((r - 2.8) / 0.15) ** 2)
    return onset + peak


def main() -> None:
    q = np.arange(20, 981) * 0.03  # 0.60 .. 29.40
    r = np.arange(1, 12001) * 0.005
    gpdf = g_to_gpdf(r, synthetic_g(r), RHO0)
    sq_true = fq_to_sq(q, gpdf_to_fq(r, gpdf, q))
    sq_meas = (sq_true - B_TRUE) / A_TRUE

    base = dict(
        qmin=0.6, qmax=30.0, rho0=RHO0, b_avg_sq=B2, r_cutoff=1.0, r0=2.5,
        r_fit_min=1.2, r_fit_max=2.25, rmax=25.0, nr=1000,
    )
    config = ScalingConfig(**base)
    auto = autoscale(q, sq_meas, config)
    sweep = level_sweep(q, sq_meas)

    head = q <= q[0] + 1.0
    _, s_true_0 = np.polyfit(q[head], sq_true[head], 1)
    fz_config = ScalingConfig(
        **base, b_sq_avg=float(B2 * (1.0 - s_true_0)), amplitude_criterion="fz"
    )
    fz = autoscale(q, sq_meas, fz_config)

    detect_config = ScalingConfig(**{**base, "r0": None, "r_fit_max": None})
    detected = autoscale(q, sq_meas, detect_config)

    manual = scale_pipeline(q, sq_meas, config, A_TRUE, B_TRUE)
    r_sample_idx = [50, 200, 500, 999]   # on the r grid (nr = 1000)
    q_sample_idx = [50, 200, 500, 950]   # on the cropped q grid (961 pts)

    payload = {
        "note": "generated by tests/generate_autoscale_fixture.py — do not edit",
        "aTrue": A_TRUE,
        "bTrue": B_TRUE,
        "config": {
            "qmin": 0.6, "qmax": 30.0, "rho0": RHO0, "bAvgSq": B2,
            "rCutoff": 1.0, "r0": 2.5, "rFitMin": 1.2, "rFitMax": 2.25,
            "rmax": 25.0, "nr": 1000,
        },
        "fzBSqAvg": float(B2 * (1.0 - s_true_0)),
        "q": q.tolist(),
        "sqMeas": sq_meas.tolist(),
        "expected": {
            "auto": {
                "a": auto.a,
                "b": auto.b,
                "iterations": auto.iterations,
                "converged": bool(auto.converged),
                "lowRRms": auto.low_r_rms,
                "c1TailMean": auto.c1_tail_mean,
            },
            "sweep": {
                "level": sweep.level,
                "levelUncertainty": sweep.level_uncertainty,
                "qLo": sweep.q_lo,
                "qHi": sweep.q_hi,
                "nAdmissible": sweep.n_admissible,
            },
            "fz": {"a": fz.a, "b": fz.b},
            "autoDetect": {
                "a": detected.a,
                "r0Detected": detected.provenance.get("r0_detected"),
                "windowRefined": bool(detected.provenance.get("window_refined", False)),
                "rFitWindow": list(detected.provenance["r_fit_window"]),
            },
            "manual": {
                "lowRRms": manual.low_r_rms,
                "c1TailMean": manual.c1_tail_mean,
                "rSampleIdx": r_sample_idx,
                "qSampleIdx": q_sample_idx,
                "gkSamples": [manual.gk[i] for i in r_sample_idx],
                "sqFilteredSamples": [manual.sq_filtered[i] for i in q_sample_idx],
            },
        },
    }
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(payload))
    print(f"wrote {OUT} ({OUT.stat().st_size} bytes)")
    print(f"auto a={auto.a} b={auto.b} iters={auto.iterations}; fz a={fz.a}; "
          f"level={sweep.level} n_adm={sweep.n_admissible}")


if __name__ == "__main__":
    main()
