# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2026 Tsung-Han Yang

"""Regenerate the JS parity golden for the triplets engine.

Writes ``web_app/frontend/src/__tests__/fixtures/triplets_fixture.json``:
deterministic input configurations plus the reference-grade Python results
(`rmc_toolkits.triplets.bond_angle_distribution`). The vitest suite runs the
`workers/triplets.js` port on the same inputs and asserts exact integer
histograms and float agreement, so regenerate this file whenever the engine's
conventions change:

    python tests/generate_triplets_fixture.py
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np

from rmc_toolkits.triplets import bond_angle_distribution, bond_angle_summary

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "web_app" / "frontend" / "src" / "__tests__" / "fixtures" / "triplets_fixture.json"


def case_random_triclinic() -> dict:
    rng = np.random.default_rng(11)
    count = 48
    positions = rng.uniform(size=(count, 3))
    elements = ["Se" if value < 0.6 else "Nb" for value in rng.uniform(size=count)]
    lattice = [[6.0, 0.0, 0.0], [3.0, 5.0, 0.0], [1.0, 1.0, 7.0]]
    return {
        "name": "random-triclinic",
        "fractional": np.round(positions, 12).tolist(),
        "elements": elements,
        "lattice": lattice,
        "specs": [
            {"triplet": ["Se", "Nb", "Se"], "bond12": [1.0, 3.4], "bond23": None, "binWidth": 5.0},
            {"triplet": ["Se", "Nb", "Nb"], "bond12": [1.0, 3.0], "bond23": [1.5, 3.4], "binWidth": 5.0},
            {"triplet": ["Se", "Se", "Se"], "bond12": [1.0, 3.2], "bond23": None, "binWidth": 2.0},
        ],
    }


def case_small_box_images() -> dict:
    return {
        "name": "small-box-images",
        "fractional": [[0.0, 0.0, 0.0], [0.25, 0.0, 0.0], [0.5, 0.55, 0.1]],
        "elements": ["Nb", "Se", "Se"],
        "lattice": [[4.0, 0.0, 0.0], [0.0, 4.0, 0.0], [0.0, 0.0, 4.0]],
        "specs": [
            {"triplet": ["Se", "Nb", "Se"], "bond12": [0.5, 3.5], "bond23": None, "binWidth": 1.0}
        ],
    }


def angle_samples(sorted_angles: np.ndarray, limit: int = 200, ends: int = 50) -> dict:
    values = [round(float(v), 6) for v in sorted_angles]
    if len(values) <= limit:
        return {"sortedAngles": values}
    return {"sortedAnglesHead": values[:ends], "sortedAnglesTail": values[-ends:]}


def evaluate(case: dict) -> dict:
    expectations = []
    for spec in case["specs"]:
        result = bond_angle_distribution(
            np.asarray(case["fractional"], dtype=float),
            case["elements"],
            np.asarray(case["lattice"], dtype=float),
            triplet=spec["triplet"],
            bond12=spec["bond12"],
            bond23=spec["bond23"],
            bin_width=spec["binWidth"],
            collect_angles=True,
        )
        def rounded(values, digits):
            return [None if v is None else round(float(v), digits) for v in values]

        expectations.append(
            {
                "counts": result.counts.tolist(),
                "density": rounded(result.density, 12),
                "sinCorrected": rounded(result.sin_corrected, 10),
                "angleCount": result.angle_count,
                "meanAngle": rounded([result.mean_angle], 8)[0],
                "stdAngle": rounded([result.std_angle], 8)[0],
                "apexCount": result.apex_count,
                "bond12Count": result.bond12_count,
                "bond23Count": result.bond23_count,
                "meanLength12": rounded([result.mean_length12], 8)[0],
                "meanLength23": rounded([result.mean_length23], 8)[0],
                # 1e-6 deg rounding: far coarser than float noise, far finer
                # than the vitest tolerance, and it keeps the fixture small.
                # Exact bin counts pin the histogram, so big cases only need
                # spot checks at the sorted list's ends (plus mean/std above).
                **angle_samples(np.sort(result.angles)),
                # The app payload: lengths + coordination parity for the port.
                "summary": bond_angle_summary(
                    np.asarray(case["fractional"], dtype=float),
                    case["elements"],
                    np.asarray(case["lattice"], dtype=float),
                    triplet=spec["triplet"],
                    bond12=spec["bond12"],
                    bond23=spec["bond23"],
                    bin_width=spec["binWidth"],
                ),
            }
        )
    return {**case, "expected": expectations}


def main() -> None:
    payload = {
        "note": "Generated by tests/generate_triplets_fixture.py -- do not edit by hand.",
        "cases": [evaluate(case_random_triclinic()), evaluate(case_small_box_images())],
    }
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(payload) + "\n", encoding="utf-8")
    print(f"wrote {OUT} ({OUT.stat().st_size // 1024} KB)")


if __name__ == "__main__":
    main()
