# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2026 Tsung-Han Yang

"""Regenerate the cross-runtime golden for a legacy coords-only ``.rmc6f``.

Writes ``web_app/frontend/src/__tests__/fixtures/rmc6f_coords_only_fixture.json``:
a coords-only configuration (``id element [label] x y z`` atom lines, no
reference-site or cell-index columns) cut from the committed demo run, plus
what the reference-grade Python FILE loaders make of it:

- ``kdePositions`` -- ``kde.load_unit_cell_positions`` (the Flask
  ``/api/kde/slice`` input), folded fractional positions in file order;
- ``triplets`` -- ``triplets.bond_angle_summary_from_file`` (the Flask
  ``/api/triplets`` body) for a few triplets.

``coordsOnlyParity.test.js`` runs the browser path on the same text (the
structure parser the KDE worker is fed from, and the shared worker's
``triplets`` request) and asserts the same atoms and the same histograms;
``tests/test_coords_only_fixture.py`` fails when the Python side drifts from
this golden. Both layouts must count: a coords-only file used to give the
Flask KDE zero positions while the browser folded every atom.

    python tests/generate_coords_only_fixture.py
"""

from __future__ import annotations

import json
from pathlib import Path
import re
import tempfile

from rmc_toolkits.kde import load_unit_cell_positions
from rmc_toolkits.triplets import bond_angle_summary_from_file

ROOT = Path(__file__).resolve().parents[1]
DEMO = ROOT / "web_app" / "frontend" / "public" / "demo" / "GTS_250K.rmc6f"
OUT = ROOT / "web_app" / "frontend" / "src" / "__tests__" / "fixtures" / "rmc6f_coords_only_fixture.json"

# A compact 2x2x2 block of unit cells, so the Ta4 clusters and TaSe6 / GaSe4
# polyhedra inside it are whole and every triplet below has angles.
BLOCK = 2

TRIPLETS = [
    {"end1": "Se", "apex": "Ta", "end2": "Se", "r12Min": 2.0, "r12Max": 3.0, "binWidth": 2.0},
    {"end1": "Ta", "apex": "Ta", "end2": "Ta", "r12Min": 2.6, "r12Max": 3.4, "binWidth": 2.0},
    {"end1": "Se", "apex": "Ga", "end2": "Se", "r12Min": 2.0, "r12Max": 3.0, "binWidth": 1.0},
    {"end1": "Se", "apex": "Ta", "end2": "Ta", "r12Min": 2.0, "r12Max": 3.0,
     "r23Min": 2.6, "r23Max": 3.4, "binWidth": 5.0},
]


def coords_only_text() -> str:
    """The demo run's atoms in the first BLOCK^3 cells, stripped to coords-only."""
    header: list[str] = []
    atoms: list[str] = []
    in_atoms = False
    with DEMO.open("r", encoding="utf-8") as handle:
        for line in handle:
            line = line.rstrip("\n")
            if not in_atoms:
                header.append(line)
                in_atoms = line.strip() == "Atoms:"
                continue
            tokens = line.split()
            if len(tokens) != 10:
                continue
            if all(0 <= int(cell) < BLOCK for cell in tokens[7:10]):
                # id element [label] x y z -- the legacy layout.
                atoms.append("   ".join(tokens[:6]))
    count = len(atoms)
    header = [re.sub(r"(Number of atoms:\s*)\d+", rf"\g<1>{count}", line) for line in header]
    return "\n".join(header + atoms) + "\n"


def evaluate(text: str) -> dict:
    with tempfile.TemporaryDirectory() as tmp:
        path = Path(tmp) / "coords_only.rmc6f"
        path.write_text(text, encoding="utf-8")
        positions = load_unit_cell_positions(path)
        expected_triplets = []
        for spec in TRIPLETS:
            summary = bond_angle_summary_from_file(
                path,
                spec["end1"], spec["apex"], spec["end2"],
                spec["r12Min"], spec["r12Max"],
                spec.get("r23Min", spec["r12Min"]), spec.get("r23Max", spec["r12Max"]),
                spec["binWidth"],
            )
            expected_triplets.append({"request": spec, "summary": summary})
    return {
        "kdePositions": {
            "count": int(len(positions.fractional_positions)),
            "fractional": positions.fractional_positions.tolist(),
        },
        "triplets": expected_triplets,
    }


def main() -> None:
    text = coords_only_text()
    payload = {
        "note": "Generated by tests/generate_coords_only_fixture.py -- do not edit by hand.",
        "rmc6f": text,
        **evaluate(text),
    }
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(payload) + "\n", encoding="utf-8")
    print(f"wrote {OUT} ({OUT.stat().st_size // 1024} KB)")


if __name__ == "__main__":
    main()
