# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2026 Tsung-Han Yang

"""Reusable analysis helpers for RMCProfile post-processing."""

__version__ = "0.4.0"

from .kde import (
    MAX_KDE_FIT_POINTS,
    UnitCellPositions,
    kde_slice,
    load_unit_cell_positions,
    oriented_kde_slice,
)
from .pca_kde import (
    MAX_PCA_FIT_POINTS,
    SiteDisplacements,
    cached_site_displacements,
    displacement_cloud,
    load_site_displacements,
    pca_kde_volume,
    probability_scale,
    site_ellipsoids,
    site_pca_kde,
)
from .parsers import (
    CsvSeries,
    Rmc6fAtom,
    RmcStructure,
    StogInput,
    frac_lines_from_rmc6f,
    iter_rmc6f_atoms,
    read_atom_indices,
    read_cell_vectors,
    read_chi,
    read_dat_header,
    read_exafs_csv,
    read_rmc_csv,
    read_stog,
    read_stog_inp,
    read_stog_xy,
    read_structure,
    rwp,
    write_frac_from_rmc6f,
    write_stog_xy,
)
from .plots import PlotResult, close_plot, detect_plot_kind, make_plot, plot_to_png
from .scattering import COHERENT_B_FM, FaberZiman, faber_ziman, parse_formula
from .scaling import (
    LevelSweepResult,
    ScalingConfig,
    ScalingResult,
    amplitude_from_fz_limit,
    autoscale,
    diagnostics_summary,
    level_sweep,
    scale_pipeline,
)
from .transforms import (
    density_line,
    enforce_low_r,
    first_peak_zero,
    fk_to_sq,
    fourier_filter,
    fq_to_gpdf,
    fq_to_sq,
    g_to_gk,
    g_to_gpdf,
    gk_to_dr,
    gk_to_g,
    gpdf_to_fq,
    gpdf_to_g,
    lorch_window,
    omitted_low_q_correction,
    sq_to_fk,
    sq_to_fq,
)

__all__ = [
    "__version__",
    "CsvSeries",
    "MAX_KDE_FIT_POINTS",
    "MAX_PCA_FIT_POINTS",
    "LevelSweepResult",
    "PlotResult",
    "Rmc6fAtom",
    "RmcStructure",
    "ScalingConfig",
    "ScalingResult",
    "SiteDisplacements",
    "StogInput",
    "UnitCellPositions",
    "COHERENT_B_FM",
    "FaberZiman",
    "amplitude_from_fz_limit",
    "autoscale",
    "density_line",
    "diagnostics_summary",
    "enforce_low_r",
    "faber_ziman",
    "first_peak_zero",
    "fk_to_sq",
    "level_sweep",
    "parse_formula",
    "fourier_filter",
    "fq_to_gpdf",
    "fq_to_sq",
    "g_to_gk",
    "g_to_gpdf",
    "gk_to_dr",
    "gk_to_g",
    "gpdf_to_fq",
    "gpdf_to_g",
    "lorch_window",
    "omitted_low_q_correction",
    "read_dat_header",
    "read_stog_inp",
    "read_stog_xy",
    "scale_pipeline",
    "sq_to_fk",
    "sq_to_fq",
    "write_stog_xy",
    "cached_site_displacements",
    "close_plot",
    "detect_plot_kind",
    "displacement_cloud",
    "frac_lines_from_rmc6f",
    "iter_rmc6f_atoms",
    "kde_slice",
    "load_site_displacements",
    "load_unit_cell_positions",
    "make_plot",
    "oriented_kde_slice",
    "pca_kde_volume",
    "plot_to_png",
    "probability_scale",
    "site_ellipsoids",
    "site_pca_kde",
    "read_atom_indices",
    "read_cell_vectors",
    "read_chi",
    "read_exafs_csv",
    "read_rmc_csv",
    "read_stog",
    "read_structure",
    "rwp",
    "write_frac_from_rmc6f",
]
